Update weProducto.yml

diff --git a/.github/workflows/weProducto.yml b/.github/workflows/weProducto.yml
--- a/.github/workflows/weProducto.yml
+++ b/.github/workflows/weProducto.yml
@@ -11,15 +11,15 @@
 name: Build and deploy Web App
 
 env:
-  AZURE_WEBAPP_NAME: persona-api    # Change this to your Azure Web App name
-  AZURE_WEBAPP_PACKAGE_PATH: './D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Helpers'
+  AZURE_WEBAPP_NAME: ProductoWeb2000    # Change this to your Azure Web App name
+  AZURE_WEBAPP_PACKAGE_PATH: './Producto.API/API'
   DOTNET_VERSION: '8.0'
 
 on:
   push:
     branches: [ "main" ]
     paths:
-      - 'D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Helpers/**'
+      - 'Producto.API/Helpers/**'
   workflow_dispatch:
 
 permissions:
@@ -46,24 +46,21 @@ jobs:
             ${{ runner.os }}-nuget-
 
       - name: Restore dependencies
-        run: dotnet restore "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Vehiculo.API.sln"
+        run: dotnet restore "Producto.API/Producto.API.sln"
 
       - name: Build with dotnet
         run: |
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Abstracciones/*.csproj" --configuration Release --no-restore
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/API/*.csproj" --configuration Release --no-restore
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/DA/*.csproj" --configuration Release --no-restore
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/DA.EF/*.csproj" --configuration Release --no-restore
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Flujo/*.csproj" --configuration Release --no-restore
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Helpers/*.csproj" --configuration Release --no-restore
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Reglas/*.csproj" --configuration Release --no-restore
-          dotnet build "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Servicios/*.csproj" --configuration Release --no-restore
+          dotnet build "Producto.API/Abstracciones/Abstracciones.csproj" --configuration Release --no-restore
+          dotnet build "Producto.API/API/API.csproj" --configuration Release --no-restore
+          dotnet build "Producto.API/DA/DA.csproj" --configuration Release --no-restore
+          dotnet build "Producto.API/Flujo/Flujo.csproj" --configuration Release --no-restore
+          
 
       - name: Run tests
-        run: dotnet test "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Vehiculo.API.sln" --no-restore --verbosity normal --configuration Release || echo "No tests found or test execution failed"
+        run: dotnet test "Producto.API/Producto.API.sln" --no-restore --verbosity normal --configuration Release || echo "No tests found or test execution failed"
 
       - name: dotnet publish
-        run: dotnet publish "D:/Code/2025C02/Semana 09-Documentos/Vehiculo.API/Helpers/*.csproj" -c Release -o ./publish --no-restore
+        run: dotnet publish "Vehiculos.WEB/Web/Web.csproj" -c Release -o ./publish --no-restore
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
@@ -91,6 +88,6 @@ jobs:
         uses: azure/webapps-deploy@v3
         with:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
-          publish-profile: ${{ secrets.AZURE_WEB2APP_PUBLISH_PROFILE }}
+          publish-profile: ${{ secrets.AZURE_PRO2APP_PUBLISH_PROFILE }}
           package: .
           respect-funcignore: true
